language: node_js

node_js:
  - '10'

branch:
  only:
    - master

install: npm install

cache:
  directories:
    - 'node_modules'

jobs:
  include:
    - stage: Run Tests
      node_js: '10'
      script:
        - npm run test